name: test ccache

on:
  push:
    paths:
      - '.github/workflows/test_ccache.yml'
      - 'Tools/scripts/build_tests/test_ccache.py'
      - 'ArduCopter/**'
      - 'modules/**'
      - 'libraries/**'
      - 'Tools/ardupilotwaf/**'
      - 'wscript'

  pull_request:
    paths:
      - '.github/workflows/test_ccache.yml'
      - 'Tools/scripts/build_tests/test_ccache.py'
      - 'ArduCopter/**'
      - 'modules/**'
      - 'libraries/**'
      - 'Tools/ardupilotwaf/**'
      - 'wscript'

  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ardupilot/ardupilot-dev-${{ matrix.toolchain }}:latest
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        toolchain: [
            chibios,
        ]
        gcc: [10]
    steps:
      # git checkout the PR
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: ccache test
        shell: bash
        run: |
          PATH="/usr/lib/ccache:/opt/gcc-arm-none-eabi-${{matrix.gcc}}/bin:$PATH"
          Tools/scripts/build_tests/test_ccache.py --boards MatekF405,MatekF405-bdshot --min-cache-pct=75
          Tools/scripts/build_tests/test_ccache.py --boards CubeOrange,Durandal --min-cache-pct=75

