name: test dds

on:
  push:
    paths:
      - '.github/workflows/test_dds.yml'
      - 'Tools/scripts/build_ci.sh'
      - 'AntennaTracker/**'
      - 'ArduCopter/**'
      - 'ArduPlane/**'
      - 'ArduSub/**'
      - 'Rover/**'
      - 'Blimp/**'
      - 'Tools/AP_Bootloader/**'
      - 'Tools/AP_Periph/**'
      - 'modules/**'
      - 'libraries/**'
      - 'Tools/ardupilotwaf/**'
      - 'wscript'
      - 'Tools/autotest/param_metadata/param_parse.py'
      - 'Tools/scripts/configure_all.py'
      - 'Tools/autotest/test_build_options.py'
      - 'Tools/scripts/signing/generate_keys.py'
      - 'Tools/scripts/build_bootloaders.py'
      - 'Tools/scripts/signing/**'

  pull_request:
    paths:
      - '.github/workflows/test_chibios.yml'
      - 'Tools/scripts/build_ci.sh'
      - 'ArduCopter/**'
      - 'ArduPlane/**'
      - 'modules/**'
      - 'libraries/**'
      - 'Tools/ardupilotwaf/**'
      - 'wscript'

  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: ardupilot/ardupilot-dev-ros:latest
      options: --user 1001
    strategy:
      fail-fast: false  # don't cancel if a job from the matrix fails
      matrix:
        config: [
            sitl,
            stm32h7
        ]
    steps:
      # git checkout the PR
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      # Put ccache into github cache for faster build
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
      - name: ccache cache files
        uses: actions/cache@v3
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{ matrix.config }}-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-${{ matrix.config }}-  # restore ccache from either previous build on this branch or on master
      - name: setup ccache
        run: |
          . .github/workflows/ccache.env
      - name: test ${{matrix.config}}
        env:
          CI_BUILD_TARGET: dds-${{matrix.config}}
        shell: 'script -q -e -c "bash {0}"'
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          PATH="/github/home/.local/bin:$PATH"
          Tools/scripts/build_ci.sh

      - name: Archive buildlog artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
           name: fail-${{matrix.config}}
           path: /tmp/buildlogs
           retention-days: 14
